# Generated by Django 6.0.5 on 2026-06-02 02:58

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.CharField(max_length=10)),
                ('aircraft_type', models.CharField(max_length=50)),
                ('serial_number', models.CharField(blank=True, max_length=50)),
                ('engine_count', models.IntegerField(default=1)),
                ('seats', models.IntegerField(default=2)),
                ('records_hobbs', models.BooleanField(default=True)),
                ('records_tacho', models.BooleanField(default=False)),
                ('records_airswitch', models.BooleanField(default=False)),
                ('total_time_method', models.CharField(choices=[('hobbs', 'Hobbs Meter'), ('tacho', 'Tachometer'), ('tacho_less_5', 'Tacho - 5%')], default='hobbs', max_length=20)),
                ('fuel_consumption_per_hour', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('status', models.CharField(choices=[('online', 'Online'), ('maintenance', 'In Maintenance'), ('grounded', 'Grounded'), ('retired', 'Retired')], default='online', max_length=20)),
                ('is_available_for_hire', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['registration'],
            },
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('timezone', models.CharField(default='Pacific/Auckland', max_length=50)),
                ('currency', models.CharField(default='NZD', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('caa_number', models.CharField(blank=True, max_length=10)),
                ('phone_mobile', models.CharField(blank=True, max_length=20)),
                ('phone_home', models.CharField(blank=True, max_length=20)),
                ('phone_work', models.CharField(blank=True, max_length=20)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('suburb', models.CharField(blank=True, max_length=100)),
                ('postcode', models.CharField(blank=True, max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AircraftMaintenanceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('due_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('last_completed_date', models.DateField(blank=True, null=True)),
                ('last_completed_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('urgency', models.CharField(choices=[('green', 'Within limits'), ('amber', 'Due soon'), ('red', 'Overdue/grounded')], default='green', max_length=10)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_items', to='core.aircraft')),
            ],
            options={
                'ordering': ['due_date', 'due_hours'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_start', models.DateTimeField()),
                ('scheduled_end', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_maintenance_booking', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='core.aircraft')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings_confirmed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings_created', to=settings.AUTH_USER_MODEL)),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flights_instructed', to=settings.AUTH_USER_MODEL)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='core.club')),
            ],
            options={
                'ordering': ['-scheduled_start'],
            },
        ),
        migrations.CreateModel(
            name='BookingAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('confirmed', 'Confirmed'), ('field_changed', 'Field Changed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('warning_acknowledged', 'Warning Acknowledged')], max_length=30)),
                ('field_name', models.CharField(blank=True, max_length=100)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='core.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Booking Audit Logs',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='aircraft',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aircraft', to='core.club'),
        ),
        migrations.CreateModel(
            name='ClubMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'Member'), ('instructor', 'Instructor'), ('admin', 'Admin'), ('staff', 'Staff')], default='member', max_length=20)),
                ('join_date', models.DateField(auto_now_add=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.club')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__last_name'],
                'unique_together': {('user', 'club')},
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='core.clubmember'),
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club_member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='core.clubmember')),
            ],
            options={
                'verbose_name_plural': 'Accounts',
            },
        ),
        migrations.CreateModel(
            name='FlightCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobbs_start', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('hobbs_end', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('tacho_start', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('tacho_end', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('actual_flight_hours', models.DecimalField(decimal_places=2, max_digits=6)),
                ('base_charge', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fuel_surcharge', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('landing_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('other_charges', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_charge', models.DecimalField(decimal_places=2, max_digits=8)),
                ('payment_method', models.CharField(choices=[('credit', 'Account Credit'), ('eftpos', 'EFTPOS'), ('invoice', 'Invoice (Bank Transfer)')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flight_completion', to='core.booking')),
                ('logged_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FlightType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('is_billable', models.BooleanField(default=True)),
                ('is_training', models.BooleanField(default=False)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_types', to='core.club')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('club', 'code')},
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='flight_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.flighttype'),
        ),
        migrations.CreateModel(
            name='MemberCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_type', models.CharField(choices=[('ppl', 'Private Pilot Licence'), ('commercial', 'Commercial Licence'), ('atpl', 'Airline Transport Pilot'), ('instructor', 'Instructor Rating'), ('bfr', 'Biennial Flight Review'), ('medical_c1', 'Class 1 Medical'), ('medical_c2', 'Class 2 Medical')], max_length=20)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('certificate_number', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='core.clubmember')),
            ],
            options={
                'ordering': ['-expiry_date'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='aircraft',
            unique_together={('club', 'registration')},
        ),
        migrations.CreateModel(
            name='ChargeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_method', models.CharField(choices=[('hobbs', 'Hobbs Hour'), ('tacho', 'Tachometer Hour')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('currency', models.CharField(default='NZD', max_length=3)),
                ('includes_fuel', models.BooleanField(default=False)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_rates', to='core.aircraft')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_rates', to='core.club')),
                ('flight_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_rates', to='core.flighttype')),
            ],
            options={
                'unique_together': {('aircraft', 'flight_type', 'time_method')},
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['club', 'scheduled_start'], name='core_bookin_club_id_532216_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['member', 'status'], name='core_bookin_member__9cdec0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='membercredential',
            unique_together={('club_member', 'credential_type')},
        ),
    ]
