# Generated by Django 6.0.5 on 2026-06-02 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubmember',
            name='member_status',
            field=models.CharField(choices=[('member', 'Member'), ('non_member', 'Non-Member')], default='member', max_length=20),
        ),
        migrations.AlterField(
            model_name='clubmember',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='club_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ClubConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_booking_duration', models.IntegerField(default=90, help_text='Minutes')),
                ('time_slot_interval', models.IntegerField(default=30, help_text='Minutes')),
                ('operating_hours_start', models.TimeField(default='07:00')),
                ('operating_hours_end', models.TimeField(default='21:00')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='core.club')),
            ],
        ),
        migrations.CreateModel(
            name='MembershipCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_member', models.BooleanField(default=True, help_text='True=member, False=non-member')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_categories', to='core.club')),
            ],
            options={
                'verbose_name_plural': 'Membership categories',
                'unique_together': {('club', 'name')},
            },
        ),
        migrations.AddField(
            model_name='clubmember',
            name='membership_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.membershipcategory'),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='core.club')),
            ],
            options={
                'unique_together': {('club', 'name')},
            },
        ),
        migrations.AlterField(
            model_name='clubmember',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.role'),
        ),
        migrations.CreateModel(
            name='MemberCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('status', models.CharField(choices=[('member', 'Member'), ('non_member', 'Non-Member')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_categories', to='core.club')),
            ],
            options={
                'ordering': ['status', 'name'],
                'unique_together': {('club', 'slug')},
            },
        ),
    ]
