# Generated by Django 6.0.5 on 2026-06-02 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_clubmember_member_status_alter_clubmember_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='blockout_conflict',
            field=models.BooleanField(default=False, help_text='Set when a block-out was added over this existing booking. Staff must resolve.'),
        ),
        migrations.AddField(
            model_name='booking',
            name='blockout_conflict_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='blockout_override',
            field=models.BooleanField(default=False, help_text='Set when staff deliberately booked over a block-out.'),
        ),
        migrations.CreateModel(
            name='BlockOutType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#9aa3ad', help_text='Hex colour for the calendar', max_length=7)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockout_types', to='core.club')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlockOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text="Optional note, e.g. '100hr check'", max_length=150)),
                ('scope', models.CharField(choices=[('all', 'All resources'), ('aircraft', 'Specific aircraft'), ('instructors', 'Specific instructors')], default='all', max_length=20)),
                ('recurrence', models.CharField(choices=[('one_off', 'One-off'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='one_off', max_length=10)),
                ('date', models.DateField(blank=True, help_text='For one-off blocks', null=True)),
                ('weekday', models.IntegerField(blank=True, help_text='0=Mon..6=Sun, for weekly', null=True)),
                ('all_day', models.BooleanField(default=False)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('active_from', models.DateField(blank=True, null=True)),
                ('active_until', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aircraft', models.ManyToManyField(blank=True, related_name='blockouts', to='core.aircraft')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockouts', to='core.club')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_blockouts', to=settings.AUTH_USER_MODEL)),
                ('instructors', models.ManyToManyField(blank=True, related_name='blockouts', to=settings.AUTH_USER_MODEL)),
                ('blockout_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.blockouttype')),
            ],
            options={
                'ordering': ['recurrence', 'start_time'],
            },
        ),
    ]
