# Generated by Django 6.0.5 on 2026-06-02 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_booking_blockout_conflict_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubconfig',
            name='duration_options',
            field=models.CharField(default='60,90,120,180', help_text='Comma-separated minutes offered in the booking/search duration picker', max_length=200),
        ),
    ]
