# Generated by Django 6.0.5 on 2026-06-02 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_clubconfig_duration_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubconfig',
            name='theme_accent',
            field=models.CharField(default='#e8943a', help_text='Accent / highlights', max_length=7),
        ),
        migrations.AddField(
            model_name='clubconfig',
            name='theme_atypical',
            field=models.CharField(default='#eef1f4', help_text='Outside-typical-hours shading', max_length=7),
        ),
        migrations.AddField(
            model_name='clubconfig',
            name='theme_banner',
            field=models.CharField(default='#1d3a5f', help_text='Top banner background', max_length=7),
        ),
        migrations.AddField(
            model_name='clubconfig',
            name='theme_confirmed',
            field=models.CharField(default='#2f9e44', help_text='Confirmed booking pills', max_length=7),
        ),
        migrations.AddField(
            model_name='clubconfig',
            name='theme_pending',
            field=models.CharField(default='#f08c00', help_text='Pending booking pills', max_length=7),
        ),
        migrations.AddField(
            model_name='clubconfig',
            name='theme_primary',
            field=models.CharField(default='#2f7dd1', help_text='Buttons, links, active controls', max_length=7),
        ),
        migrations.AddField(
            model_name='clubconfig',
            name='theme_weekend',
            field=models.CharField(default='#fbf3e6', help_text='Weekend shading in search', max_length=7),
        ),
    ]
