# Generated by Django 6.0.5 on 2026-06-04 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_simplify_aircraft_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubmember',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='blockouttype',
            name='is_hard',
            field=models.BooleanField(default=True, help_text='Hard: blocks bookings (staff can override). Soft: advisory — anyone can confirm and proceed. Aircraft block-out types are always hard regardless of this flag.'),
        ),
        migrations.AlterField(
            model_name='clubmember',
            name='join_date',
            field=models.DateField(auto_now_add=True, help_text='Date first admitted'),
        ),
    ]
