# Generated by Django 6.0.5 on 2026-06-04 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_avatar_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubconfig',
            name='logo',
            field=models.ImageField(blank=True, help_text='Club logo — ideally white on transparent PNG, shown in the banner', null=True, upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='clubconfig',
            name='theme_accent',
            field=models.CharField(default='#f59e0b', help_text='Accent / highlights', max_length=7),
        ),
        migrations.AlterField(
            model_name='clubconfig',
            name='theme_atypical',
            field=models.CharField(default='#f1f5f9', help_text='Outside-typical-hours shading', max_length=7),
        ),
        migrations.AlterField(
            model_name='clubconfig',
            name='theme_banner',
            field=models.CharField(default='#1b3a5c', help_text='Top banner background', max_length=7),
        ),
        migrations.AlterField(
            model_name='clubconfig',
            name='theme_confirmed',
            field=models.CharField(default='#16a34a', help_text='Confirmed booking pills', max_length=7),
        ),
        migrations.AlterField(
            model_name='clubconfig',
            name='theme_pending',
            field=models.CharField(default='#f97316', help_text='Pending booking pills', max_length=7),
        ),
        migrations.AlterField(
            model_name='clubconfig',
            name='theme_primary',
            field=models.CharField(default='#3b82f6', help_text='Buttons, links, active controls', max_length=7),
        ),
        migrations.AlterField(
            model_name='clubconfig',
            name='theme_weekend',
            field=models.CharField(default='#f0f9ff', help_text='Weekend shading in search', max_length=7),
        ),
    ]
