# Generated by Django 6.0.5 on 2026-06-04 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_logo_and_new_theme_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='slot_released',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='slot_released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='slot_released_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slots_released', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_days_ahead', models.PositiveIntegerField(blank=True, help_text='Only notify for slots starting within this many days. Null = no limit.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aircraft', models.ManyToManyField(blank=True, help_text='Notify only when one of these aircraft is freed. Empty = any aircraft.', related_name='notification_prefs', to='core.aircraft')),
                ('club_member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_prefs', to='core.clubmember')),
                ('instructors', models.ManyToManyField(blank=True, help_text='Notify only when one of these instructors is freed. Empty = any instructor.', related_name='notification_prefs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification preference',
            },
        ),
        migrations.CreateModel(
            name='SlotReleaseNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Snapshot of address at send time.', max_length=254)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release_notifications', to='core.booking')),
                ('club_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_notifications_received', to='core.clubmember')),
            ],
            options={
                'ordering': ['-sent_at'],
                'unique_together': {('booking', 'club_member')},
            },
        ),
    ]
