# Generated by Django 6.0.5 on 2026-06-04 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_slot_release_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlotWatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notified_at', models.DateTimeField(blank=True, help_text='Stamped when the slot-release email was sent to this watcher.', null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchers', to='core.booking')),
                ('club_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_slots', to='core.clubmember')),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('booking', 'club_member')},
            },
        ),
    ]
