# Generated by Django 6.0.5 on 2026-06-04 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_slot_watch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightcompletion',
            name='base_charge',
        ),
        migrations.RemoveField(
            model_name='flightcompletion',
            name='fuel_surcharge',
        ),
        migrations.RemoveField(
            model_name='flightcompletion',
            name='landing_fee',
        ),
        migrations.RemoveField(
            model_name='flightcompletion',
            name='other_charges',
        ),
        migrations.AddField(
            model_name='account',
            name='preferred_payment_method',
            field=models.CharField(blank=True, choices=[('credit', 'Account credit (auto-deduct)'), ('eftpos', 'EFTPOS'), ('invoice', 'Invoice (bank transfer)')], default='', help_text='Standing payment instruction. Can be overridden per flight.', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='arrived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='departed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='departed_without_declaration',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='departed_without_declaration_reason',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='clubmember',
            name='next_of_kin_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='clubmember',
            name='next_of_kin_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='flightcompletion',
            name='fuel_surcharge_rate_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fuel surcharge rate ($/hr) locked at time of departure', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='flightcompletion',
            name='instructor_rate_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Instructor hourly rate locked at time of check-in', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='flightcompletion',
            name='original_flight_type',
            field=models.ForeignKey(blank=True, help_text='Populated if flight type was changed from booking type at check-in', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changed_completions', to='core.flighttype'),
        ),
        migrations.AddField(
            model_name='flightcompletion',
            name='outcome',
            field=models.CharField(choices=[('completed', 'Flight completed normally'), ('aborted_ground', 'Aborted on ground (pre-takeoff)'), ('early_return_tech', 'Early return — technical'), ('early_return_wx', 'Early return — weather'), ('diverted', 'Diverted / landed away')], default='completed', max_length=30),
        ),
        migrations.AddField(
            model_name='flightcompletion',
            name='outcome_notes',
            field=models.TextField(blank=True, help_text="Required when outcome is not 'completed normally'"),
        ),
        migrations.AddField(
            model_name='flightcompletion',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flightcompletion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='flighttype',
            name='requires_declaration',
            field=models.BooleanField(default=False, help_text='Pilot must submit a pre-departure declaration before checking out (e.g. Private Hire)'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('departed', 'Departed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='flightcompletion',
            name='actual_flight_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='flightcompletion',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('credit', 'Account credit'), ('eftpos', 'EFTPOS'), ('invoice', 'Invoice (bank transfer)')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='flightcompletion',
            name='total_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.CreateModel(
            name='Aerodrome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icao_code', models.CharField(help_text='4-letter ICAO code, e.g. NZMS', max_length=4)),
                ('name', models.CharField(help_text='e.g. Masterton', max_length=200)),
                ('full_stop_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('touch_and_go_fee', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank if same as full-stop or not applicable', max_digits=8, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aerodromes', to='core.club')),
            ],
            options={
                'ordering': ['icao_code'],
                'unique_together': {('club', 'icao_code')},
            },
        ),
        migrations.CreateModel(
            name='AircraftSurchargeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surcharge_types', to='core.club')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('club', 'name')},
            },
        ),
        migrations.AddField(
            model_name='aircraft',
            name='surcharges',
            field=models.ManyToManyField(blank=True, help_text='Surcharges automatically added to every flight on this aircraft', related_name='aircraft', to='core.aircraftsurchargetype'),
        ),
        migrations.CreateModel(
            name='DepartureDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_intentions', models.TextField(help_text='Planned route and intentions')),
                ('destination', models.CharField(blank=True, help_text='Primary destination aerodrome', max_length=100)),
                ('estimated_return', models.DateTimeField(blank=True, help_text='Estimated return time — used to flag overdue aircraft', null=True)),
                ('is_cross_country', models.BooleanField(default=False)),
                ('next_of_kin_name', models.CharField(max_length=200)),
                ('next_of_kin_phone', models.CharField(max_length=20)),
                ('next_of_kin_from_profile', models.BooleanField(default=True, help_text='Was next of kin auto-filled from member profile?')),
                ('confirm_aip', models.BooleanField(default=False, verbose_name='AIP reviewed')),
                ('confirm_weather', models.BooleanField(default=False, verbose_name='Weather checked')),
                ('confirm_fuel', models.BooleanField(default=False, verbose_name='Fuel requirements confirmed')),
                ('confirm_pickets', models.BooleanField(default=False, help_text='Only required for cross-country flights', verbose_name='Pickets carried')),
                ('confirm_maps', models.BooleanField(default=False, verbose_name='Maps carried')),
                ('confirm_fuel_card', models.BooleanField(default=False, verbose_name='Fuel card carried')),
                ('confirm_afm', models.BooleanField(default=False, verbose_name='AFM in aircraft')),
                ('confirm_flight_plan', models.BooleanField(default=False, verbose_name='Flight plan filed')),
                ('is_draft', models.BooleanField(default=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('staleness_acknowledged', models.BooleanField(default=False, help_text='Pilot confirmed weather/NOTAMs re-checked when declaration is >6h old')),
                ('amended_at', models.DateTimeField(blank=True, null=True)),
                ('amendment_reason', models.CharField(blank=True, max_length=500)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authorising_instructor', models.ForeignKey(blank=True, help_text='Instructor who verbally authorised this flight. Recorded only — no active approval required.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorised_declarations', to='core.clubmember')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='declaration', to='core.booking')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_declarations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Departure declaration',
            },
        ),
        migrations.CreateModel(
            name='FlightChargeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('hire', 'Aircraft hire'), ('fuel_surcharge', 'Fuel surcharge'), ('instructor', 'Instructor fee'), ('surcharge', 'Aircraft surcharge'), ('landing', 'Landing fee'), ('one_off', 'Sundry / one-off')], max_length=20)),
                ('description', models.CharField(help_text='Mandatory for sundry items; auto-populated for standard items', max_length=300)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flight_completion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_items', to='core.flightcompletion')),
            ],
            options={
                'ordering': ['item_type', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='FlightLandingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_icao', models.CharField(blank=True, max_length=4)),
                ('custom_name', models.CharField(blank=True, max_length=200)),
                ('custom_description', models.CharField(blank=True, max_length=200)),
                ('save_as_aerodrome', models.BooleanField(default=False)),
                ('full_stops', models.PositiveIntegerField(default=0)),
                ('touch_and_goes', models.PositiveIntegerField(default=0)),
                ('total_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('aerodrome', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landing_entries', to='core.aerodrome')),
                ('flight_completion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landing_entries', to='core.flightcompletion')),
            ],
            options={
                'ordering': ['aerodrome__icao_code', 'custom_icao'],
            },
        ),
        migrations.CreateModel(
            name='FrequentPassenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('next_of_kin_name', models.CharField(max_length=200)),
                ('next_of_kin_phone', models.CharField(max_length=20)),
                ('consent_given', models.BooleanField(default=False)),
                ('consent_given_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequent_passengers', to='core.clubmember')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeclarationPassenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('next_of_kin_name', models.CharField(max_length=200)),
                ('next_of_kin_phone', models.CharField(max_length=20)),
                ('declaration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='core.departuredeclaration')),
                ('frequent_passenger', models.ForeignKey(blank=True, help_text='Source frequent-passenger record (for reference only — data is snapshotted)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declaration_appearances', to='core.frequentpassenger')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InstructorGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. C-Cat, B-Cat, A-Cat, Examiner', max_length=50)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower = shown first')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_grades', to='core.club')),
            ],
            options={
                'ordering': ['club', 'display_order', 'name'],
                'unique_together': {('club', 'name')},
            },
        ),
        migrations.AddField(
            model_name='clubmember',
            name='instructor_grade',
            field=models.ForeignKey(blank=True, help_text='Instructor qualification grade — determines hourly rate', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='core.instructorgrade'),
        ),
        migrations.CreateModel(
            name='FuelSurchargeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, help_text='Per Hobbs/Tacho hour', max_digits=8)),
                ('effective_from', models.DateField()),
                ('notes', models.CharField(blank=True, help_text="e.g. 'April price rise'", max_length=255)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_surcharge_rates', to='core.club')),
            ],
            options={
                'ordering': ['-effective_from'],
                'unique_together': {('club', 'effective_from')},
            },
        ),
    ]
