# Generated by Django 6.0.5 on 2026-06-04 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_flight_lifecycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubmember',
            name='has_admin_access',
            field=models.BooleanField(default=False, help_text='Grants access to club Settings regardless of role. Use for CFIs and club secretaries who manage the system.'),
        ),
        migrations.AlterField(
            model_name='aerodrome',
            name='notes',
            field=models.TextField(blank=True, help_text='Agreement terms, billing cycle, contact info, anything instructors need to know'),
        ),
    ]
