# Generated by Django 6.0.5 on 2026-06-04 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_admin_access_aerodrome_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flightlandingentry',
            options={'ordering': ['aerodrome__icao_code', 'custom_icao', 'fee_type_name']},
        ),
        migrations.AlterModelOptions(
            name='fuelsurchargerate',
            options={'ordering': ['-effective_from'], 'verbose_name': 'Fuel rate'},
        ),
        migrations.AlterUniqueTogether(
            name='fuelsurchargerate',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='aerodrome',
            name='full_stop_fee',
        ),
        migrations.RemoveField(
            model_name='aerodrome',
            name='touch_and_go_fee',
        ),
        migrations.RemoveField(
            model_name='flightlandingentry',
            name='custom_description',
        ),
        migrations.RemoveField(
            model_name='flightlandingentry',
            name='full_stops',
        ),
        migrations.RemoveField(
            model_name='flightlandingentry',
            name='touch_and_goes',
        ),
        migrations.AddField(
            model_name='aircraft',
            name='hire_includes_fuel',
            field=models.BooleanField(default=True, help_text='Wet hire — fuel is included in the hire rate. Uncheck for dry hire where fuel is charged separately per hour.'),
        ),
        migrations.AddField(
            model_name='flightlandingentry',
            name='fee_type_name',
            field=models.CharField(default='', help_text='Pre-filled from fee type; editable for custom entries', max_length=100),
        ),
        migrations.AddField(
            model_name='flightlandingentry',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='flightlandingentry',
            name='unit_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Rate at time of logging (snapshot of fee_type.default_amount or manually entered)', max_digits=8),
        ),
        migrations.AddField(
            model_name='fuelsurchargerate',
            name='aircraft',
            field=models.ForeignKey(blank=True, help_text='Leave blank for a club-wide rate; set for a per-aircraft override.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fuel_rates', to='core.aircraft'),
        ),
        migrations.AlterField(
            model_name='flightchargeitem',
            name='item_type',
            field=models.CharField(choices=[('hire', 'Aircraft hire'), ('fuel', 'Fuel'), ('instructor', 'Instructor fee'), ('surcharge', 'Aircraft surcharge'), ('landing', 'Landing fee'), ('one_off', 'Sundry / one-off')], max_length=20),
        ),
        migrations.AlterField(
            model_name='flightlandingentry',
            name='save_as_aerodrome',
            field=models.BooleanField(default=False, help_text='Offer to save this custom aerodrome to the configured list'),
        ),
        migrations.AlterField(
            model_name='fuelsurchargerate',
            name='notes',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='AerodromeFeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Full stop, Touch & go, Night surcharge', max_length=100)),
                ('default_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('aerodrome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_types', to='core.aerodrome')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('aerodrome', 'name')},
            },
        ),
        migrations.AddField(
            model_name='flightlandingentry',
            name='fee_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landing_entries', to='core.aerodromefeetype'),
        ),
    ]
