# Generated by Django 6.0.5 on 2026-06-04 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_aerodrome_fee_types_fuel_rates'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubconfig',
            name='cancellation_fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Fee charged for late cancellations. Set to 0 to disable automatic prompting.', max_digits=8),
        ),
        migrations.AddField(
            model_name='clubconfig',
            name='cancellation_notice_hours',
            field=models.PositiveIntegerField(default=24, help_text='Bookings cancelled within this many hours of the start time may incur a fee'),
        ),
        migrations.CreateModel(
            name='AccountTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('top_up', 'Account top-up'), ('flight', 'Flight charge'), ('cancellation', 'Cancellation fee'), ('adjustment', 'Manual adjustment')], max_length=20)),
                ('direction', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=6)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Always positive; direction determines credit/debit', max_digits=10)),
                ('description', models.CharField(help_text='Mandatory — shown on account statement', max_length=300)),
                ('payment_method', models.CharField(blank=True, choices=[('bank_transfer', 'Bank transfer'), ('eftpos', 'EFTPOS'), ('cash', 'Cash'), ('account', 'Account credit'), ('other', 'Other')], max_length=20)),
                ('reference', models.CharField(blank=True, help_text='Bank reference, receipt number, cheque number etc.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.account')),
                ('booking', models.ForeignKey(blank=True, help_text='Set for cancellation fee transactions', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_transactions', to='core.booking')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_transactions', to=settings.AUTH_USER_MODEL)),
                ('flight_completion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_transactions', to='core.flightcompletion')),
            ],
            options={
                'verbose_name': 'Account transaction',
                'ordering': ['-created_at'],
            },
        ),
    ]
