# Generated by Django 6.0.5 on 2026-06-04 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_account_transactions_cancellation_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aircraft',
            name='hire_includes_fuel',
        ),
        migrations.AddField(
            model_name='aircraft',
            name='hobbs_initial',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Hobbs reading when aircraft was entered into the system', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='tacho_initial',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tacho reading when aircraft was entered into the system', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='clubmember',
            name='standing',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('active', 'Active'), ('suspended', 'Suspended'), ('lapsed', 'Lapsed'), ('resigned', 'Resigned'), ('transferred', 'Transferred'), ('non_member', 'Non-member')], default='active', max_length=20),
        ),
        migrations.DeleteModel(
            name='MemberCategory',
        ),
    ]
