# Generated by Django 6.0.5 on 2026-06-05 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_cleanup_and_initial_meters'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubconfig',
            name='theme_completed_paid',
            field=models.CharField(default='#7c3aed', help_text='Completed & paid booking pills', max_length=7),
        ),
        migrations.AddField(
            model_name='clubconfig',
            name='theme_departed',
            field=models.CharField(default='#d97706', help_text='Departed booking pills', max_length=7),
        ),
        migrations.AddField(
            model_name='clubconfig',
            name='theme_returned',
            field=models.CharField(default='#2563eb', help_text='Returned (awaiting payment) booking pills', max_length=7),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('departed', 'Departed'), ('completed', 'Returned'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
