# Generated by Django 6.0.5 on 2026-06-05 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_theme_flight_status_colours'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightcompletion',
            name='meter_gap_note',
            field=models.TextField(blank=True, default='', help_text="Explanation required when start reading doesn't match the previous flight's end reading"),
        ),
    ]
