# Generated by Django 6.0.5 on 2026-06-05 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_meter_gap_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='airswitch_initial',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Air switch reading when aircraft was entered into the system', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='flightcompletion',
            name='airswitch_end',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='flightcompletion',
            name='airswitch_start',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='total_time_method',
            field=models.CharField(choices=[('hobbs', 'Hobbs Meter'), ('tacho', 'Tachometer'), ('tacho_less_5', 'Tacho - 5%'), ('airswitch', 'Air Switch')], default='hobbs', max_length=20),
        ),
        migrations.AlterField(
            model_name='chargerate',
            name='time_method',
            field=models.CharField(choices=[('hobbs', 'Hobbs Hour'), ('tacho', 'Tachometer Hour'), ('airswitch', 'Air Switch Hour')], max_length=20),
        ),
    ]
