# Generated by Django 6.0.5 on 2026-06-05 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_airswitch_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelsurchargerate',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to pause fuel charging without deleting the rate'),
        ),
    ]
