# Generated by Django 6.0.5 on 2026-06-05 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_fuel_rate_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membercredential',
            options={'ordering': ['credential_type', '-expiry_date']},
        ),
        migrations.AlterUniqueTogether(
            name='membercredential',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='membercredential',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credentials_added', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membercredential',
            name='evidence',
            field=models.ImageField(blank=True, null=True, upload_to='credentials/'),
        ),
        migrations.AddField(
            model_name='membercredential',
            name='name',
            field=models.CharField(blank=True, help_text='Specific name — required for Type Rating and Other', max_length=100),
        ),
        migrations.AlterField(
            model_name='membercredential',
            name='credential_type',
            field=models.CharField(choices=[('spl', 'Student Pilot Licence'), ('ppl', 'Private Pilot Licence (PPL)'), ('cpl', 'Commercial Pilot Licence (CPL)'), ('atpl', 'Air Transport Pilot Licence (ATPL)'), ('xc', 'Cross Country Endorsement'), ('night_vfr', 'Night VFR Endorsement'), ('ir', 'Instrument Rating (IR)'), ('me', 'Multi-Engine Rating'), ('type', 'Type Rating'), ('aerobatic', 'Aerobatic Endorsement'), ('seaplane', 'Seaplane Rating'), ('instr_c', 'Instructor Certificate — C-Cat'), ('instr_b', 'Instructor Certificate — B-Cat'), ('instr_a', 'Instructor Certificate — A-Cat'), ('examiner', 'Flight Examiner'), ('medical_c1', 'Medical Certificate — Class 1'), ('medical_c2', 'Medical Certificate — Class 2'), ('medical_c3', 'Medical Certificate — Class 3'), ('fr', 'Flight Review'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='membercredential',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='membercredential',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
