# Generated by Django 6.0.5 on 2026-06-05 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_credential_expansion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membercredential',
            name='credential_type',
            field=models.CharField(choices=[('ppl', 'Private Pilot Licence (PPL)'), ('cpl', 'Commercial Pilot Licence (CPL)'), ('atpl', 'Air Transport Pilot Licence (ATPL)'), ('xc', 'Cross Country Endorsement'), ('night_vfr', 'Night VFR Endorsement'), ('ir', 'Instrument Rating (IR)'), ('me', 'Multi-Engine Rating'), ('type', 'Type Rating'), ('tailwheel', 'Tailwheel Endorsement'), ('aerobatic', 'Aerobatic Endorsement'), ('seaplane', 'Seaplane Rating'), ('instr_c', 'Instructor Certificate — C-Cat'), ('instr_b', 'Instructor Certificate — B-Cat'), ('instr_a', 'Instructor Certificate — A-Cat'), ('examiner', 'Flight Examiner'), ('medical_c1', 'Medical Certificate — Class 1'), ('medical_c2', 'Medical Certificate — Class 2'), ('medical_c3', 'Medical Certificate — Class 3'), ('dlr9', 'DLR9 Medical'), ('fr', 'Flight Review (BFR)'), ('other', 'Other')], max_length=20),
        ),
    ]
