# Generated by Django 6.0.5 on 2026-06-05 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_membercredential_credential_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightcompletion',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
