# Generated by Django 6.0.5 on 2026-06-05 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_aircraft_type_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubconfig',
            name='bank_account',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='clubconfig',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='clubconfig',
            name='billing_address',
            field=models.TextField(blank=True, help_text='Postal address printed on invoices'),
        ),
        migrations.AddField(
            model_name='clubconfig',
            name='billing_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='clubconfig',
            name='billing_name',
            field=models.CharField(blank=True, help_text="Legal name on invoices, e.g. 'Wellington Aero Club Inc.'", max_length=200),
        ),
        migrations.AddField(
            model_name='clubconfig',
            name='billing_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='clubconfig',
            name='gst_number',
            field=models.CharField(blank=True, help_text='GST / tax registration number', max_length=30),
        ),
        migrations.AddField(
            model_name='clubconfig',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, default=15, help_text='GST rate as a percentage, e.g. 15 for 15%', max_digits=5),
        ),
        migrations.AddField(
            model_name='clubconfig',
            name='invoice_number_next',
            field=models.PositiveIntegerField(default=1, help_text='Next invoice number to allocate — set this to continue from your current sequence'),
        ),
        migrations.AddField(
            model_name='clubconfig',
            name='invoice_number_prefix',
            field=models.CharField(blank=True, help_text="Optional prefix, e.g. 'INV-'", max_length=10),
        ),
        migrations.AddField(
            model_name='clubconfig',
            name='payment_terms_days',
            field=models.PositiveIntegerField(default=14, help_text='Days from invoice date until payment is due'),
        ),
        migrations.AddField(
            model_name='clubconfig',
            name='payment_terms_text',
            field=models.TextField(blank=True, help_text='Payment instructions printed on invoice footer'),
        ),
        migrations.AlterField(
            model_name='membercredential',
            name='name',
            field=models.CharField(blank=True, help_text='Specific name — required for Other; supplementary for Type Rating (e.g. specific aircraft reg)', max_length=100),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.PositiveIntegerField()),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent — awaiting payment'), ('paid', 'Paid'), ('void', 'Void')], default='draft', max_length=10)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=15, max_digits=5)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='core.club')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_created', to=settings.AUTH_USER_MODEL)),
                ('flight_completion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='core.flightcompletion')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='core.clubmember')),
            ],
            options={
                'ordering': ['-invoice_number'],
                'unique_together': {('club', 'invoice_number')},
            },
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sort_order', models.IntegerField(default=0)),
                ('charge_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_lines', to='core.flightchargeitem')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='core.invoice')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
