# Generated by Django 6.0.5 on 2026-06-05 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_invoice_billing'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='is_leased',
            field=models.BooleanField(default=False, help_text='Leased-in aircraft (not club-owned)'),
        ),
    ]
