# Generated by Django 6.0.5 on 2026-06-05 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_is_leased'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubconfig',
            name='bfr_interval_months',
            field=models.PositiveIntegerField(default=24, help_text='Flight Review required every N months (club policy)'),
        ),
        migrations.AddField(
            model_name='clubconfig',
            name='medical_class1_over40',
            field=models.PositiveIntegerField(default=6),
        ),
        migrations.AddField(
            model_name='clubconfig',
            name='medical_class1_under40',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AddField(
            model_name='clubconfig',
            name='medical_class2_over40',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AddField(
            model_name='clubconfig',
            name='medical_class2_under40',
            field=models.PositiveIntegerField(default=24),
        ),
        migrations.AddField(
            model_name='clubconfig',
            name='medical_class3_over40',
            field=models.PositiveIntegerField(default=24),
        ),
        migrations.AddField(
            model_name='clubconfig',
            name='medical_class3_under40',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='clubconfig',
            name='medical_warning_days',
            field=models.PositiveIntegerField(default=30, help_text='Warn when a medical expires within this many days'),
        ),
        migrations.AddField(
            model_name='clubconfig',
            name='recency_warning_days',
            field=models.PositiveIntegerField(default=90, help_text="Warn when a member hasn't flown an aircraft type in this many days (solo/private flights)"),
        ),
    ]
