# Generated by Django 6.0.5 on 2026-06-06 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_compliance_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubconfig',
            name='fy_start_month',
            field=models.PositiveSmallIntegerField(default=4, help_text='Month the financial year starts (1=Jan … 12=Dec). NZ default: April (4)'),
        ),
    ]
