# Generated by Django 6.0.5 on 2026-06-06 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_fy_start_month'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aircraftmaintenanceitem',
            options={'ordering': ['urgency', 'due_date', 'due_hours']},
        ),
        migrations.AddField(
            model_name='aircraft',
            name='maint_hours_initial',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maintenance hours already accumulated when aircraft was entered into this system', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='maint_time_fraction',
            field=models.DecimalField(decimal_places=2, default='1.00', help_text='Fraction of raw reading counted as maintenance hours (e.g. 0.95 = 95% of tacho)', max_digits=4),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='maint_time_source',
            field=models.CharField(choices=[('hobbs', 'Hobbs Meter'), ('tacho', 'Tachometer'), ('airswitch', 'Air Switch')], default='hobbs', help_text='Which instrument to use when accumulating maintenance hours', max_length=10),
        ),
        migrations.AddField(
            model_name='aircraftmaintenanceitem',
            name='alert_days',
            field=models.IntegerField(blank=True, help_text='Red alert when this many days remain until due date', null=True),
        ),
        migrations.AddField(
            model_name='aircraftmaintenanceitem',
            name='alert_hours',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Red alert when this many maintenance hours remain', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='aircraftmaintenanceitem',
            name='interval_days',
            field=models.IntegerField(blank=True, help_text='Recurring calendar interval in days (e.g. 365 for annual)', null=True),
        ),
        migrations.AddField(
            model_name='aircraftmaintenanceitem',
            name='interval_hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Recurring interval in maintenance hours (e.g. 100 for a 100-hour check)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='aircraftmaintenanceitem',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aircraftmaintenanceitem',
            name='warn_days',
            field=models.IntegerField(blank=True, help_text='Amber warning when this many days remain until due date', null=True),
        ),
        migrations.AddField(
            model_name='aircraftmaintenanceitem',
            name='warn_hours',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Amber warning when this many maintenance hours remain (default from ClubConfig)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='clubconfig',
            name='maint_alert_days',
            field=models.PositiveIntegerField(default=14, help_text='Default: go red when this many days remain until a date-based item is due'),
        ),
        migrations.AddField(
            model_name='clubconfig',
            name='maint_alert_hours',
            field=models.DecimalField(decimal_places=1, default=5, help_text='Default: go red when this many maintenance hours remain', max_digits=6),
        ),
        migrations.AddField(
            model_name='clubconfig',
            name='maint_warn_days',
            field=models.PositiveIntegerField(default=30, help_text='Default: go amber when this many days remain until a date-based item is due'),
        ),
        migrations.AddField(
            model_name='clubconfig',
            name='maint_warn_hours',
            field=models.DecimalField(decimal_places=1, default=20, help_text='Default: go amber when this many maintenance hours remain', max_digits=6),
        ),
        migrations.AlterField(
            model_name='aircraftmaintenanceitem',
            name='due_hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cumulative maintenance hours at which this item is next due', max_digits=8, null=True),
        ),
        migrations.CreateModel(
            name='MaintenanceLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hobbs_reading', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('tacho_reading', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('airswitch_reading', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('maint_hours_flight', models.DecimalField(decimal_places=2, default=0, help_text='Maintenance hours accrued this flight (source × fraction)', max_digits=7)),
                ('maint_hours_total', models.DecimalField(decimal_places=2, default=0, help_text='Cumulative maintenance hours for this aircraft after this entry', max_digits=8)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maint_log', to='core.aircraft')),
                ('flight_completion', models.OneToOneField(blank=True, help_text='Set when auto-created from a flight check-in', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maint_log_entry', to='core.flightcompletion')),
            ],
            options={
                'ordering': ['date', 'id'],
            },
        ),
    ]
