# Generated by Django 6.0.5 on 2026-06-06 03:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_maintenance_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique code printed on voucher', max_length=30)),
                ('description', models.CharField(blank=True, help_text="E.g. 'Harbour Circuit Trial Flight'", max_length=200)),
                ('value', models.DecimalField(decimal_places=2, help_text='Credit amount in club currency', max_digits=8)),
                ('is_redeemed', models.BooleanField(default=False)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='core.club')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_vouchers', to=settings.AUTH_USER_MODEL)),
                ('redeemed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redeemed_vouchers', to='core.clubmember')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('club', 'code')},
            },
        ),
    ]
