# Generated by Django 6.0.5 on 2026-06-06 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_voucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='departuredeclaration',
            name='sar_time',
            field=models.DateTimeField(blank=True, help_text='SARTIME — the date/time at which SAR should be notified if the aircraft has not returned', null=True),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='total_time_method',
            field=models.CharField(choices=[('hobbs', 'Hobbs Meter'), ('tacho', 'Tachometer'), ('tacho_less_5', 'Tachometer (legacy — now treated as plain Tacho for billing)'), ('airswitch', 'Air Switch')], default='hobbs', max_length=20),
        ),
    ]
