# Generated by Django 6.0.5 on 2026-06-06 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_instructor_roster'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancellation_reason',
            field=models.CharField(blank=True, choices=[('weather', 'Weather'), ('aircraft_unserviceable', 'Aircraft unserviceable'), ('instructor_unavailable', 'Instructor unavailable'), ('no_longer_required', 'No longer required'), ('other', 'Other')], max_length=30),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancellation_reason_other',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='clubmember',
            name='is_on_instructor_roster',
            field=models.BooleanField(default=False, help_text='Appears as an instructor row in the calendar and is selectable on bookings. Requires the member to have an instructor-type role.'),
        ),
    ]
