# Generated by Django 6.0.5 on 2026-06-06 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_cancellation_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='booking_cancelled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='booking_confirmed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='booking_reminder',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='credential_expiring',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='instructor_booking_upcoming',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='instructor_booking_urgent',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='lapsed_credentials',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='maintenance_alert',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='subscription_expiring',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('booking_confirmed', 'Booking confirmed'), ('booking_cancelled', 'Booking cancelled'), ('booking_reminder', 'Booking reminder'), ('credential_expiring', 'Credential expiring'), ('subscription_expiring', 'Subscription expiring'), ('instructor_booking_urgent', 'New booking assigned (urgent)'), ('instructor_booking_upcoming', 'New booking assigned'), ('maintenance_alert', 'Maintenance alert'), ('lapsed_credentials', 'Lapsed credentials — flight today')], max_length=40)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('action_url', models.CharField(blank=True, max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('club_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.clubmember')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
