# Generated by Django 6.0.5 on 2026-06-06 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='slot_released',
            field=models.BooleanField(default=False),
        ),
    ]
