# Generated by Django 6.0.5 on 2026-06-06 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_add_slot_released_pref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='flights_instructed', to=settings.AUTH_USER_MODEL),
        ),
    ]
