# Generated by Django 6.0.5 on 2026-06-07 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_booking_instructor_protect'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='system_role_type',
            field=models.CharField(blank=True, choices=[('member', 'Member'), ('instructor', 'Instructor'), ('admin', 'Admin')], default='', help_text='Set for the three built-in roles (member/instructor/admin). Permissions are locked.', max_length=20),
        ),
    ]
