# Generated by Django 6.0.5 on 2026-06-08 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_migrate_payments'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'departed')), fields=('aircraft',), name='unique_aircraft_departed'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'departed')), fields=('member',), name='unique_member_departed'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('instructor__isnull', False), ('status', 'departed')), fields=('instructor',), name='unique_instructor_departed'),
        ),
    ]
