# Generated by Django 6.0.5 on 2026-06-08 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_unique_departed_constraints'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='unique_aircraft_departed',
        ),
        migrations.RemoveConstraint(
            model_name='booking',
            name='unique_member_departed',
        ),
        migrations.RemoveConstraint(
            model_name='booking',
            name='unique_instructor_departed',
        ),
    ]
