# Generated by Django 6.0.5 on 2026-06-08 01:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_remove_departed_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightcompletion',
            name='departed_with_aircraft',
            field=models.ForeignKey(blank=True, help_text='Aircraft that physically departed — may differ from booking.aircraft if swapped mid-flight', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departed_completions', to='core.aircraft'),
        ),
        migrations.AddField(
            model_name='flightcompletion',
            name='departed_with_instructor',
            field=models.ForeignKey(blank=True, help_text='Instructor at departure — may differ from booking.instructor if swapped mid-flight', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departed_completions', to=settings.AUTH_USER_MODEL),
        ),
    ]
