# Generated by Django 6.0.5 on 2026-06-08 03:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_flightcompletion_departure_snapshots'),
    ]

    operations = [
        migrations.CreateModel(
            name='OccurrenceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrence_types', to='core.club')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'unique_together': {('club', 'name')},
            },
        ),
        migrations.CreateModel(
            name='OccurrenceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('closed', 'Closed')], default='submitted', max_length=20)),
                ('date_of_occurrence', models.DateField()),
                ('time_of_occurrence', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, help_text='Aerodrome ICAO, airspace, or description', max_length=200)),
                ('description', models.TextField(help_text='Describe what happened')),
                ('immediate_action', models.TextField(blank=True, help_text='Any immediate action taken')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aircraft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occurrence_reports', to='core.aircraft')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrence_reports', to='core.club')),
                ('related_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occurrence_reports', to='core.booking')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='occurrence_reports', to='core.clubmember')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_occurrences', to=settings.AUTH_USER_MODEL)),
                ('occurrence_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='core.occurrencetype')),
            ],
            options={
                'ordering': ['-reported_at'],
            },
        ),
    ]
