# Generated by Django 6.0.5 on 2026-06-08 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_role_fleet_safety'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttransaction',
            name='transaction_type',
            field=models.CharField(choices=[('top_up', 'Account top-up'), ('flight', 'Flight charge'), ('cancellation', 'Cancellation fee'), ('adjustment', 'Manual adjustment'), ('sale', 'Sundry sale')], max_length=20),
        ),
        migrations.AlterField(
            model_name='occurrencereport',
            name='is_safety_risk',
            field=models.BooleanField(default=False, help_text='Reporter or reviewer flagged as potential safety risk'),
        ),
        migrations.AlterField(
            model_name='role',
            name='can_access_fleet',
            field=models.BooleanField(default=False, help_text='Access to Fleet section (aircraft management)'),
        ),
        migrations.AlterField(
            model_name='role',
            name='can_access_manage',
            field=models.BooleanField(default=False, help_text='Access to Operations and People (bookings, members, block-outs, sales)'),
        ),
        migrations.AlterField(
            model_name='role',
            name='can_access_reports',
            field=models.BooleanField(default=False, help_text='Access to Analytics and Reports'),
        ),
        migrations.AlterField(
            model_name='role',
            name='can_access_safety',
            field=models.BooleanField(default=False, help_text='Access to Safety section (events review, action items)'),
        ),
        migrations.AlterField(
            model_name='role',
            name='can_access_settings',
            field=models.BooleanField(default=False, help_text='Access to Configuration (settings, types)'),
        ),
        migrations.AlterField(
            model_name='role',
            name='is_superadmin',
            field=models.BooleanField(default=False, help_text='Full access to everything — all permissions implied'),
        ),
        migrations.CreateModel(
            name='FlightSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveSmallIntegerField()),
                ('hobbs_start', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('hobbs_end', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('tacho_start', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('tacho_end', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('airswitch_start', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('airswitch_end', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('flight_completion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='core.flightcompletion')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flight_segments', to='core.clubmember')),
            ],
            options={
                'ordering': ['sequence'],
                'unique_together': {('flight_completion', 'sequence')},
            },
        ),
        migrations.AddField(
            model_name='flightchargeitem',
            name='segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charge_items', to='core.flightsegment'),
        ),
    ]
