# Generated by Django 6.0.5 on 2026-06-08 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_flight_segment'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='billed_to',
            field=models.CharField(blank=True, choices=[('contact', 'Client pays'), ('organisation', 'Organisation invoiced'), ('club', 'Club absorbs')], default='', help_text='Only relevant when a non-member client is set.', max_length=20),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('is_organisation', models.BooleanField(default=False, help_text='Organisation account (school, company). Cannot be converted to a member.')),
                ('organisation', models.CharField(blank=True, help_text='For individuals: sponsoring school or organisation.', max_length=200)),
                ('contact_type', models.CharField(choices=[('trial_flight', 'Trial flight'), ('young_eagle', 'Young Eagles / Gateway'), ('commercial', 'Commercial client'), ('guest', 'Guest'), ('other', 'Other')], default='other', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='core.club')),
                ('converted_to_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_from_contact', to='core.clubmember')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Non-member being flown (trial flight, Young Eagles, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='core.contact'),
        ),
    ]
