# Generated by Django 6.0.5 on 2026-06-08 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_contact_type_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubmember',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='', max_length=1),
        ),
    ]
