# Generated by Django 6.0.5 on 2026-06-08 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_add_sex_to_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubmember',
            name='resigned_at',
            field=models.DateField(blank=True, help_text='Date membership formally ceased (ISA 2022 s.26)', null=True),
        ),
        migrations.AlterField(
            model_name='clubmember',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], default='', max_length=1),
        ),
        migrations.CreateModel(
            name='MembershipHistoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('joined', 'Joined'), ('standing_change', 'Standing changed'), ('category_change', 'Membership category changed'), ('role_change', 'Role changed'), ('subscription_renewed', 'Subscription renewed'), ('note', 'Note')], max_length=30)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('old_value', models.CharField(blank=True, max_length=200)),
                ('new_value', models.CharField(blank=True, max_length=200)),
                ('note', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('club_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_history', to='core.clubmember')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
