# Generated by Django 6.0.5 on 2026-06-09 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_membership_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubconfig',
            name='theme_accent',
            field=models.CharField(default='#d4732a', help_text='Accent / highlights', max_length=7),
        ),
        migrations.AlterField(
            model_name='clubconfig',
            name='theme_atypical',
            field=models.CharField(default='#f0f0f0', help_text='Outside-typical-hours shading', max_length=7),
        ),
        migrations.AlterField(
            model_name='clubconfig',
            name='theme_banner',
            field=models.CharField(default='#2b2b2b', help_text='Top banner background', max_length=7),
        ),
        migrations.AlterField(
            model_name='clubconfig',
            name='theme_pending',
            field=models.CharField(default='#e8a800', help_text='Pending booking pills', max_length=7),
        ),
        migrations.AlterField(
            model_name='clubconfig',
            name='theme_primary',
            field=models.CharField(default='#c0481c', help_text='Buttons, links, active controls', max_length=7),
        ),
        migrations.AlterField(
            model_name='clubconfig',
            name='theme_weekend',
            field=models.CharField(default='#fdf0e6', help_text='Weekend shading in search', max_length=7),
        ),
        migrations.CreateModel(
            name='VoucherType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('default_value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.CharField(blank=True, help_text='Default description printed on the voucher', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_types', to='core.club')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'unique_together': {('club', 'name')},
            },
        ),
    ]
