# Generated by Django 6.0.5 on 2026-06-09 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_voucher_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlyingBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fy_year', models.PositiveSmallIntegerField(help_text='Year the FY starts (e.g. 2025 for Jul 2025–Jun 2026)')),
                ('month', models.PositiveSmallIntegerField(help_text='Month number 1–12')),
                ('budgeted_hours', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='core.aircraft')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flying_budgets', to='core.club')),
            ],
            options={
                'ordering': ['aircraft__registration', 'fy_year', 'month'],
                'unique_together': {('club', 'aircraft', 'fy_year', 'month')},
            },
        ),
    ]
