# Generated by Django 6.0.5 on 2026-06-10 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_flying_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubconfig',
            name='chart_colors',
            field=models.JSONField(default=list, help_text='Ordered list of hex colours used in charts. Should have 8–10 distinct colours that complement the primary theme.'),
        ),
    ]
