# Generated by Django 6.0.5 on 2026-06-12 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_remove_tacho_less5'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubconfig',
            name='lapse_grace_days',
            field=models.PositiveIntegerField(default=60, help_text='Days after subscription_expires before a member is auto-lapsed. Run manage.py update_lapsed_members (or use Settings) to apply.'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='total_time_method',
            field=models.CharField(choices=[('hobbs', 'Hobbs Meter'), ('tacho', 'Tachometer'), ('airswitch', 'Air Switch')], default='hobbs', max_length=20),
        ),
    ]
