# Generated by Django 6.0.5 on 2026-06-13 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_weatherwebcam_embed_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherwebcam',
            name='url',
            field=models.URLField(help_text="Webcam page link (used for 'Open' button)", max_length=500),
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.TextField(unique=True)),
                ('p256dh', models.TextField()),
                ('auth', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('club_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to='core.clubmember')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
