# Generated by Django 6.0.5 on 2026-06-13 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_push_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubconfig',
            name='mobile_booking_slots',
            field=models.TextField(blank=True, default='', help_text='Comma-separated HH:MM-HH:MM slot pairs for the mobile booking finder, e.g. 08:00-09:30, 09:00-10:30, 10:00-11:30'),
        ),
    ]
