# Generated by Django 6.0.5 on 2026-06-13 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_clubconfig_mobile_booking_slots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubconfig',
            name='mobile_booking_slots',
        ),
        migrations.AddField(
            model_name='clubconfig',
            name='booking_slots',
            field=models.TextField(blank=True, default='', help_text='Comma-separated HH:MM-HH:MM slot pairs, e.g. 08:30-10:00, 10:00-11:30, 12:30-14:00'),
        ),
    ]
