# Generated by Django 6.0.5 on 2026-06-14 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_rename_mobile_booking_slots_to_booking_slots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubconfig',
            name='font_choice',
            field=models.CharField(choices=[('system', 'System default'), ('inter', 'Inter (modern sans-serif)'), ('poppins', 'Poppins (geometric sans-serif)'), ('nunito', 'Nunito (rounded, friendly)'), ('lora', 'Lora (elegant serif)')], default='system', help_text='Body font used across all pages.', max_length=20),
        ),
        migrations.AlterField(
            model_name='membercredential',
            name='evidence',
            field=models.FileField(blank=True, null=True, upload_to='credentials/'),
        ),
    ]
