# Generated by Django 6.0.5 on 2026-06-14 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubconfig',
            name='booking_block_credit_limit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Block when account balance goes below negative this amount (e.g. 200 = block at −$200). Leave blank to disable.', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='clubconfig',
            name='booking_block_enabled',
            field=models.BooleanField(default=False, help_text='Enable financial booking blocks. Individual conditions below must also be configured.'),
        ),
        migrations.AddField(
            model_name='clubconfig',
            name='booking_block_invoice_days',
            field=models.PositiveIntegerField(blank=True, help_text='Block when an invoice is older than this many days and still unpaid. Leave blank to disable.', null=True),
        ),
        migrations.AddField(
            model_name='clubconfig',
            name='booking_block_message',
            field=models.TextField(blank=True, help_text='Message shown to a blocked member. If blank, auto-generated from billing phone/email.'),
        ),
        migrations.AddField(
            model_name='clubconfig',
            name='booking_block_unpaid_flight_days',
            field=models.PositiveIntegerField(blank=True, help_text='Block when a flight charge has been unpaid for more than this many days. Leave blank to disable.', null=True),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='status',
            field=models.CharField(choices=[('online', 'Active'), ('retired', 'Retired')], default='online', max_length=20),
        ),
    ]
