# Generated by Django 6.0.5 on 2026-06-15 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_booking_block_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='subscription_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
