# Generated by Django 6.0.5 on 2026-06-15 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_notif_pref_payment_invoice_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Issued'), ('paid', 'Paid'), ('void', 'Void')], default='draft', max_length=10),
        ),
    ]
