# Generated by Django 6.0.5 on 2026-06-16 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_feedbackmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraftmaintenanceitem',
            name='urgency',
            field=models.CharField(choices=[('green', 'OK'), ('amber', 'Due soon'), ('red', 'Due / Overdue')], default='green', max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flights_instructed', to=settings.AUTH_USER_MODEL),
        ),
    ]
