# Generated by Django 6.0.5 on 2026-06-18 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_clubmember_membership_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacttype',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='contacttype',
            name='sort_order',
        ),
    ]
