# Generated by Django 6.0.5 on 2026-06-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_remove_contact_type_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubconfig',
            name='compact_mode',
            field=models.BooleanField(default=False, help_text='Reduce padding and font sizes for denser layouts.'),
        ),
    ]
