# Generated by Django 6.0.5 on 2026-06-18 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_add_compact_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubconfig',
            name='app_banner',
            field=models.ImageField(blank=True, help_text='Hero image shown on the mobile app home screen. Landscape, ~3:1 ratio (e.g. 1200×400px). JPG or PNG.', null=True, upload_to='app_banners/'),
        ),
    ]
