# Generated by Django 6.0.5 on 2026-06-19 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_invoice_payment_ledger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightpayment',
            name='method',
            field=models.CharField(choices=[('credit', 'Account credit'), ('eftpos', 'EFTPOS'), ('cash', 'Cash'), ('invoice', 'Invoice (bank transfer)'), ('refund', 'Refund')], max_length=20),
        ),
    ]
