# Generated by Django 6.0.5 on 2026-06-20 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0090_flighttype_for_contacts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubconfig',
            name='theme_completed_paid',
        ),
        migrations.RemoveField(
            model_name='clubconfig',
            name='theme_confirmed',
        ),
        migrations.RemoveField(
            model_name='clubconfig',
            name='theme_departed',
        ),
        migrations.RemoveField(
            model_name='clubconfig',
            name='theme_pending',
        ),
        migrations.RemoveField(
            model_name='clubconfig',
            name='theme_returned',
        ),
        migrations.AddField(
            model_name='clubconfig',
            name='dual_accent',
            field=models.CharField(default='#1D9E75', help_text='Dual-flight pairing accent colour', max_length=7),
        ),
    ]
