# Generated by Django 6.0.5 on 2026-06-22 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0092_credential_catalogue'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membercredential',
            options={'ordering': ['credential_type__display_order', 'credential_type__name', '-expiry_date']},
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('departed', 'Departed'), ('completed', 'Returned'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='credentialtype',
            name='code',
            field=models.CharField(help_text="Short stable identifier, e.g. 'ppl', 'medical_c2'", max_length=20),
        ),
        migrations.AlterField(
            model_name='credentialtype',
            name='default_validity_months',
            field=models.IntegerField(blank=True, help_text='Convenience default for pre-filling expiry date; actual expiry stored per-credential', null=True),
        ),
        migrations.AlterField(
            model_name='credentialtype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='credentialtype',
            name='region',
            field=models.CharField(db_index=True, default='NZ-CAA', help_text='Jurisdiction, e.g. NZ-CAA, AU-CASA', max_length=20),
        ),
        migrations.AlterField(
            model_name='credentialtype',
            name='requires_aircraft_type',
            field=models.BooleanField(default=False, help_text='True for type ratings — member credential must reference a specific aircraft type'),
        ),
        migrations.AlterField(
            model_name='membercredential',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('booking_confirmed', 'Booking confirmed'), ('booking_cancelled', 'Booking cancelled'), ('booking_reminder', 'Booking reminder'), ('credential_expiring', 'Credential expiring'), ('subscription_expiring', 'Subscription expiring'), ('instructor_booking_urgent', 'New booking assigned (urgent)'), ('instructor_booking_upcoming', 'New booking assigned'), ('maintenance_alert', 'Maintenance alert'), ('lapsed_credentials', 'Lapsed credentials — flight today'), ('safety_action', 'Safety action assigned')], max_length=40),
        ),
        migrations.CreateModel(
            name='LessonNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercises_covered', models.TextField(blank=True)),
                ('debrief_notes', models.TextField(blank=True)),
                ('next_lesson_plan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_lesson_notes', to=settings.AUTH_USER_MODEL)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_note', to='core.booking')),
            ],
            options={
                'ordering': ['-booking__scheduled_start'],
            },
        ),
    ]
