# Generated by Django 6.0.5 on 2026-06-22 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_lesson_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightcompletion',
            name='time_if_actual',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual instrument flight time (hrs)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='flightcompletion',
            name='time_if_simulated',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Simulated instrument flight time (hrs)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='flightcompletion',
            name='time_low_flying',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Low flying time (hrs)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='flightcompletion',
            name='time_night',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Night flying time (hrs)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='flightcompletion',
            name='time_terrain_awareness',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Terrain awareness flying time (hrs)', max_digits=5, null=True),
        ),
    ]
