# Generated by Django 6.0.5 on 2026-06-22 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0094_special_flight_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightcompletion',
            name='invoice_issued',
            field=models.BooleanField(default=False, help_text='True when at least one active invoice exists for this flight'),
        ),
    ]
