# Generated by Django 6.0.5 on 2026-06-23 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0096_backfill_invoice_issued'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightsegment',
            name='time_if_actual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='flightsegment',
            name='time_if_simulated',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='flightsegment',
            name='time_low_flying',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='flightsegment',
            name='time_night',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='flightsegment',
            name='time_terrain_awareness',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
