# Generated by Django 6.0.5 on 2026-06-23 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0099_fix_departed_instructor_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightpayment',
            name='batch_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
