# Generated by Django 6.0.5 on 2026-06-24 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0100_add_fp_batch_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='fuel_rate_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fuel surcharge rate ($/hr) locked at departure', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='flightcompletion',
            name='pilot',
            field=models.ForeignKey(blank=True, help_text='Pilot who flew this flight (defaults to booking.member if null)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flight_completions', to='core.clubmember'),
        ),
        migrations.AlterField(
            model_name='flightcompletion',
            name='sequence',
            field=models.PositiveIntegerField(default=1, help_text='Order within the booking (1-based)'),
        ),
    ]
