# Generated by Django 6.0.5 on 2026-06-25 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0101_alter_booking_fuel_rate_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightcompletion',
            name='charge_waived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flightcompletion',
            name='waive_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='flightcompletion',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('credit', 'Account credit'), ('eftpos', 'EFTPOS'), ('invoice', 'Invoice (bank transfer)'), ('split', 'Shared'), ('cash', 'Cash')], default='', max_length=20),
        ),
    ]
