# Generated by Django 6.0.5 on 2026-06-26 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0103_clubconfig_dark_mode'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['club', 'status', 'scheduled_start'], name='core_bookin_club_id_df37b0_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['club', 'status'], name='core_bookin_club_id_dc31cc_idx'),
        ),
    ]
