# Generated by Django 6.0.5 on 2026-06-27 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0105_invoice_early_bird'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubconfig',
            name='renewal_early_bird_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='clubconfig',
            name='renewal_early_bird_cutoff',
            field=models.DateField(blank=True, null=True),
        ),
    ]
