# Generated by Django 6.0.5 on 2026-06-27 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0106_renewal_early_bird_defaults'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubconfig',
            name='renewal_early_bird_cutoff',
        ),
        migrations.AddField(
            model_name='clubconfig',
            name='renewal_early_bird_days_before_fy_end',
            field=models.PositiveIntegerField(blank=True, help_text='Days before the FY end date that the early-bird cutoff falls. e.g. 60 → cutoff is 60 days before 31 March.', null=True),
        ),
    ]
