# Generated by Django 6.0.5 on 2026-06-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0107_renewal_early_bird_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraftsurchargetype',
            name='rate_type',
            field=models.CharField(choices=[('each', 'Per flight'), ('per_hour', 'Per hour')], default='each', max_length=10),
        ),
    ]
