# Generated by Django 6.0.5 on 2026-06-27 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0108_surcharge_rate_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aircraftsurchargetype',
            name='rate_type',
        ),
    ]
