# Generated by Django 6.0.5 on 2026-06-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0109_remove_surcharge_rate_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='default_hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
