# Generated by Django 6.0.5 on 2026-06-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0110_add_aircraft_default_hourly_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraftsurchargetype',
            name='rate_type',
            field=models.CharField(choices=[('per_flight', 'Per flight'), ('per_hour', 'Per hour')], default='per_flight', max_length=10),
        ),
    ]
