# Generated by Django 6.0.5 on 2026-06-28 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0112_replace_compact_mode_with_density'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargerate',
            name='time_method',
            field=models.CharField(choices=[('hobbs', 'Hobbs'), ('tacho', 'Tacho'), ('airswitch', 'Air switch')], max_length=20),
        ),
        migrations.AlterField(
            model_name='clubconfig',
            name='font_choice',
            field=models.CharField(choices=[('system', 'System default'), ('inter', 'Inter (modern sans-serif)'), ('nunito', 'Nunito (rounded, friendly)'), ('lora', 'Lora (elegant serif)')], default='system', help_text='Body font used across all pages.', max_length=20),
        ),
        migrations.CreateModel(
            name='MaintenanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('interval_days', models.IntegerField(blank=True, null=True)),
                ('interval_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('warn_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('alert_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('warn_days', models.IntegerField(blank=True, null=True)),
                ('alert_days', models.IntegerField(blank=True, null=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_types', to='core.club')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('club', 'name')},
            },
        ),
        migrations.AddField(
            model_name='aircraftmaintenanceitem',
            name='maintenance_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='core.maintenancetype'),
        ),
    ]
