# Generated by Django 6.0.5 on 2026-06-29 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0113_maintenance_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancetype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
