# Generated by Django 6.0.5 on 2026-06-30 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0114_maintenance_type_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubmember',
            name='has_superadmin_access',
            field=models.BooleanField(default=False, help_text='Grants superadmin status regardless of role — required for destructive operations (delete, void, integrity fixes).'),
        ),
    ]
