# Generated by Django 6.0.5 on 2026-06-30 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0115_add_has_superadmin_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional photo — displayed in the mobile app. Deleted automatically when the announcement expires.', null=True, upload_to='announcements/'),
        ),
    ]
