# Generated by Django 6.0.5 on 2026-07-01 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0116_add_announcement_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubconfig',
            name='member_id_prefix',
            field=models.CharField(blank=True, help_text="Prefix for member IDs shown in the mobile app, e.g. 'WAC-'", max_length=10),
        ),
    ]
