# Generated by Django 6.0.5 on 2026-07-01 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0117_add_member_id_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrenceaction',
            name='completion_note',
            field=models.TextField(blank=True),
        ),
    ]
