from django.urls import path, re_path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('calendar/<slug:club_slug>/', views.gantt_day, name='gantt_day'),
    path('calendar/<slug:club_slug>/<int:year>/<int:month>/<int:day>/', views.gantt_day, name='gantt_day_date'),
    path('api/booking/create/', views.create_booking, name='create_booking'),
    path('api/booking/<int:booking_id>/edit/', views.edit_booking, name='edit_booking'),
    path('api/booking/<int:booking_id>/reschedule/', views.reschedule_booking, name='reschedule_booking'),
    path('api/booking/<int:booking_id>/reschedule-options/', views.reschedule_options, name='reschedule_options'),
    path('api/booking/<int:booking_id>/update/', views.update_booking, name='update_booking'),
    path('api/booking/<int:booking_id>/confirm/', views.confirm_booking, name='confirm_booking'),
    path('api/booking/<int:booking_id>/depart/', views.depart_booking, name='depart_booking'),
    path('api/booking/<int:booking_id>/checkin/', views.checkin_booking, name='checkin_booking'),
    path('api/booking/<int:booking_id>/reject/', views.reject_booking, name='reject_booking'),
    path('api/booking/<int:booking_id>/watch/', views.toggle_watch, name='toggle_watch'),
    path('api/booking/<int:booking_id>/credential-check/', views.credential_check_api, name='credential_check'),
    path('api/booking/<int:booking_id>/prev-readings/', views.prev_readings_api, name='prev_readings'),
    path('search/<slug:club_slug>/', views.availability_search, name='availability_search'),
    path('rates/<slug:club_slug>/', views.club_rates, name='club_rates'),
    path('settings/<slug:club_slug>/', views.club_settings, name='club_settings'),
    path('manage/<slug:club_slug>/', views.manage_bookings, name='manage_bookings'),
    path('manage/<slug:club_slug>/bookings/<int:booking_id>/', views.booking_detail, name='booking_detail'),
    path('manage/<slug:club_slug>/blockouts/', views.manage_blockouts, name='manage_blockouts'),
    path('manage/<slug:club_slug>/members/', views.manage_members, name='manage_members'),
    path('manage/<slug:club_slug>/members/<int:member_id>/', views.manage_member_detail, name='manage_member_detail'),
    path('manage/<slug:club_slug>/aircraft/', views.manage_aircraft, name='manage_aircraft'),
    path('manage/<slug:club_slug>/aircraft/<int:aircraft_id>/', views.manage_aircraft_detail, name='manage_aircraft_detail'),
    path('manage/<slug:club_slug>/instructors/', views.manage_instructors, name='manage_instructors'),
    path('manage/<slug:club_slug>/instructors/<int:member_id>/', views.manage_instructor_detail, name='manage_instructor_detail'),
    path('profile/<slug:club_slug>/', views.my_profile, name='my_profile'),
    path('api/blockout/create/', views.create_blockout, name='create_blockout'),
    path('manage/<slug:club_slug>/charges/', views.manage_charges, name='manage_charges'),
    path('manage/<slug:club_slug>/aerodromes/', views.manage_aerodromes, name='manage_aerodromes'),
    path('manage/<slug:club_slug>/bookings/<int:booking_id>/declaration/', views.booking_declaration, name='booking_declaration'),
    path('manage/<slug:club_slug>/rates/', views.manage_rates, name='manage_rates'),
    path('manage/<slug:club_slug>/invoices/', views.manage_invoices, name='manage_invoices'),
    path('reports/<slug:club_slug>/', views.reports, name='reports'),
    path('manage/<slug:club_slug>/bookings/<int:booking_id>/generate-invoice/', views.generate_invoice, name='generate_invoice'),
    path('manage/<slug:club_slug>/invoices/<int:invoice_id>/', views.invoice_detail, name='invoice_detail'),
    path('manage/<slug:club_slug>/invoices/<int:invoice_id>/print/', views.invoice_print, name='invoice_print'),
]
